function Hd = HPF_LS_05Hz(Fs)
%HPF_LS_0.5HZ Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.2 and the Signal Processing Toolbox 6.20.
% Generated on: 21-Nov-2017 11:29:51

% FIR least-squares Highpass filter designed using the FIRLS function.

% All frequency values are in Hz.
% Fs = 100;  % Sampling Frequency
if ~exist('Fs','var')
    Fs = 100;
elseif isempty(Fs)
    Fs = 100;
end
dur = 10;
N = ceil(Fs*dur);   % Order
if mod(N,2)         % make sure order is even
    N = N+1;
end
Fstop = 0.25;   % Stopband Frequency
Fpass = 0.5;  % Passband Frequency
Wstop = 1;     % Stopband Weight
Wpass = 0.01;  % Passband Weight

% Calculate the coefficients using the FIRLS function.
b  = firls(N, [0 Fstop Fpass Fs/2]/(Fs/2), [0 0 1 1], [Wstop Wpass]);
Hd = dfilt.dffir(b);

% [EOF]
